version: '3.5'
services:
  web:
    image: steveltn/https-portal:1
    container_name: web222
    restart: always
    #volumesセクション自体、現時点で不要
    # volumes:
    #   - ../nginx/ssl_certs:/var/lib/https-portal
    #   - ../nginx/conf/mysite_nginx.conf:/etc/nginx/conf.d/mysite_nginx.conf
    #   - ../nginx/conf/mysite_nginx.conf:/var/lib/nginx-conf/vccmarsh.link.conf.erb:ro
    #   - ../nginx/uwsgi_params:/etc/nginx/uwsgi_params
    #   # - ../src/static:/static
    #   - ../static:/static

    ports:
      - '80:80'
      - '443:443'
    environment:
      #DOMAINS: 'vccmarsh.link -> http://web:8080/'
      DOMAINS: 'vccmarsh.link -> http://django:8001'
      STAGE: 'local'
      #FORCE_RENEW: 'true'
    depends_on:
      - django

  django:
    # build: ../django
    build: .
    container_name: django222
    volumes:
      # - ./src:/code
      - ../:/code:cached
    expose:
      - '8001'
    #command: uwsgi --socket :8001 --module mysite.wsgi
    command: python3 manage.py runserver 0.0.0.0:8001
    depends_on:
      - db

  db:
    # image: postgres:latest
    image: postgres
    container_name: db222
    volumes:
      # - ../db-data:/var/lib/postgresql/data
      - db-data:/var/lib/postgresql/data
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db

volumes:
    db-data: